### ISSUE TITLE
Рабиение по пакетам

### ISSUE THREAD

**Issue by khda91** [tanya00pm/Homework-2_task-1#1]
Отсутствует разбиение по пакетам классов. Все классы сложены в один пакет.

**Comment by tanya00pm** [comment]
Для сущностей выделила пакет ru.levelup.tatiana_nesterova.qa.homework2.entities
Для интерфейсов  - ru.levelup.tatiana_nesterova.qa.homework2.entities.interfaces

**Comment by khda91** [comment]
closed
