### ISSUE TITLE
Naming convention for variables in Java

### ISSUE THREAD

**Issue by khda91** [tanya00pm/Homework-2_task-1#2]
https://github.com/tanya00pm/Homework-2_task-1/blob/bbbd074f67bd82c884bb17a88aea45b60122d789/Vehicle.java#L32

Переменные не соответствуют Java naming convention

Исправить необходимо везде где встречается наименование переменных через _

**Comment by tanya00pm** [comment]
исправлено

**Comment by khda91** [comment]
closed
