### ISSUE TITLE
Тип параметра передоваемого в метод

### ISSUE THREAD

**Issue by khda91** [tanya00pm/Homework-2_task-1#3]
https://github.com/tanya00pm/Homework-2_task-1/blob/bbbd074f67bd82c884bb17a88aea45b60122d789/Vehicle.java#L124

Необходимо ли передавать в данный метод тип Object?

**Comment by tanya00pm** [comment]
Исправила параметр с Object на Vehicle

**Comment by khda91** [comment]
closed
